### ISSUE TITLE
StopIteration exception end of video file and Make video does not output video

### ISSUE THREAD

**Issue by Sweta-codes** [creotiv/object_detection_projects#15]
After the traffic_capacity.py reaches the end of the 'input.mp4' video file, it throws a StopIteration exception as follows:

Traceback (most recent call last):
  File "traffic_capacity.py", line 72, in <module>
    main()
  File "traffic_capacity.py", line 61, in main
    cap.next()
StopIteration

Also the **make_video.sh** file is not creating an output video for traffic capacity example.

**Comment by creotiv** [comment]
fixed traffic_capacity.py by adding try catch. make_video.sh depends on
ffmpeg converter which you must have installed

Kindly yours,
Andrey Nikishaev

Areas         ML/DS/CV/Soft Dev/BizDev/Growth Hacking/Customer Rel/IT
LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Slideshare  https://www.slideshare.net/anikishaev/
Skype         creotiv.in.ua
Mobile        +380632410666

**Comment by Sweta-codes** [comment]
I have cloned the repository with your latest commit with a try-catch block, I'm still getting the StopIteration exception.

Also, I do have ffmpeg installed and the make_video.sh script is running perfectly fine with the traffic counting project, just not with traffic capacity.

**Comment by Sweta-codes** [comment]
Trying to run  make_video.sh  gives the following exception:

Could find no file with path './out/processed_%04d.png' and index in the range 0-4
./out/processed_%04d.png: No such file or directory

**Comment by harshsp31** [comment]
@Sweta-codes @creotiv  I face the same error with make_video.sh 
Did you guys find any solution?
